name: build

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Init ASIO
        run: |
          git clone https://github.com/chriskohlhoff/asio.git -b asio-1-24-0 --depth=1

      - name: CMake Build
        env:
          ASIO_PATH: asio/asio/include
        run: |
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -DASIO_NET_DISABLE_ON_DATA_PRINT=ON -DASIO_NET_ENABLE_SSL=ON ..
          make -j2

      - name: Test TCP
        run: |
          cd build
          ./asio_net_test_tcp

      - name: Test TCP (big data)
        run: |
          cd build
          ./asio_net_test_tcp_bigdata

      - name: Test TCP (reconnect)
        run: |
          cd build
          ./asio_net_test_tcp_reconnect

      - name: Test UDP
        run: |
          cd build
          ./asio_net_test_udp

      - name: Test RPC
        run: |
          cd build
          ./asio_net_test_rpc

      - name: Test RPC (rpc_config)
        run: |
          cd build
          ./asio_net_test_rpc_config

      - name: Test RPC (reconnect)
        run: |
          cd build
          ./asio_net_test_rpc_reconnect

      - name: Test RPC (ssl)
        run: |
          cd build
          #./asio_net_test_rpc_ssl
          echo "skip for avoid wait too long"

      - name: Test Domain TCP
        run: |
          cd build
          ./asio_net_test_domain_tcp

      - name: Test Domain UDP
        run: |
          cd build
          ./asio_net_test_domain_udp

      - name: Test Domain RPC
        run: |
          cd build
          ./asio_net_test_domain_rpc
