name: CI

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build-and-test:

    name: ${{ matrix.toolchain }}-${{ matrix.configuration }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        toolchain:
          - linux-gcc
          - macos-clang
          - windows-msvc
          - windows-mingw

        configuration:
          - Debug
          - Release

        include:
          - toolchain: linux-gcc
            os: ubuntu-latest
            compiler: gcc
            env:
              CMAKE_OPTIONS: "-DASIO_NET_ENABLE_SSL=ON"

          - toolchain: macos-clang
            os: macos-latest
            compiler: clang
            env:
              CMAKE_OPTIONS: "-DASIO_NET_ENABLE_SSL=ON"

          - toolchain: windows-msvc
            os: windows-latest
            compiler: msvc
            env:
              BIN_SUFFIX: ".exe"

          - toolchain: windows-mingw
            os: windows-latest
            compiler: mingw
            env:
              BIN_SUFFIX: ".exe"
              CMAKE_OPTIONS: "-G \"MinGW Makefiles\""

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Init ASIO
        run: git clone https://github.com/chriskohlhoff/asio.git -b asio-1-30-2 --depth=1

      - name: Configure (${{ matrix.configuration }})
        env:
          ASIO_PATH: asio/asio/include
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} ${{ matrix.env.CMAKE_OPTIONS }} -DASIO_NET_DISABLE_ON_DATA_PRINT=ON

      - name: Build with ${{ matrix.compiler }}
        run: cmake --build build --config ${{ matrix.configuration }}

      - name: Windows-MSVC Compatible
        if: matrix.os == 'windows-latest' && matrix.compiler == 'msvc'
        working-directory: build
        run: Move-Item -Path .\${{ matrix.configuration }}\* -Destination .\

      - name: Test TCP
        working-directory: build
        run: ./asio_net_test_tcp${{ matrix.env.BIN_SUFFIX }}

      - name: Test TCP (big data)
        working-directory: build
        run: ./asio_net_test_tcp_bigdata${{ matrix.env.BIN_SUFFIX }}

      - name: Test TCP (reconnect)
        working-directory: build
        run: ./asio_net_test_tcp_reconnect${{ matrix.env.BIN_SUFFIX }}

      - name: Test UDP
        working-directory: build
        run: ./asio_net_test_udp${{ matrix.env.BIN_SUFFIX }}

      - name: Test RPC
        working-directory: build
        run: ./asio_net_test_rpc${{ matrix.env.BIN_SUFFIX }}

      - name: Test RPC (rpc_config)
        working-directory: build
        run: ./asio_net_test_rpc_config${{ matrix.env.BIN_SUFFIX }}

      - name: Test RPC (reconnect)
        working-directory: build
        run: ./asio_net_test_rpc_reconnect${{ matrix.env.BIN_SUFFIX }}

      - name: Test RPC (ssl)
        working-directory: build
        run: ./asio_net_test_rpc_ssl${{ matrix.env.BIN_SUFFIX }}

      - name: Test Domain TCP
        if: matrix.os != 'windows-latest'
        working-directory: build
        run: ./asio_net_test_domain_tcp${{ matrix.env.BIN_SUFFIX }}

      - name: Test Domain UDP
        if: matrix.os != 'windows-latest'
        working-directory: build
        run: ./asio_net_test_domain_udp${{ matrix.env.BIN_SUFFIX }}

      - name: Test Domain RPC
        if: matrix.os != 'windows-latest'
        working-directory: build
        run: ./asio_net_test_domain_rpc${{ matrix.env.BIN_SUFFIX }}
